config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index"

  resources :cart_items

  resources :users

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session

  get "/cdash" => "cdash#index"
  post "/cdash" => "cdash#create"

  get "/contact" => "contact#index"
  post "/contact" => "contact#popup"

  get "/about" => "about#index"

  post "/cart_items" => "cart_items#coupancheck", as: :coupon_path

  resources :menus
  resources :orders

  delete "/menu_items/:id" => "menu_items#destroy"
  get "/menu_items" => "menu_items#index"
  get "/active-menu" => "menus#active_menu"
  post "/menu_items" => "menu_items#create"
  put "/menu_items/:id" => "menu_items#update"
  get "/orders" => "orders#index", as: :orders_report
  post "/link_menu_items/:id1/:id2" => "link_menu_items#create"
  delete "/link_menu_items/:id1/:id2" => "link_menu_items#destroy"
  put "/orders/:id" => "orders#update"
  get "/users-list" => "menus#userslist"
  get "clerks-list" => "menus#clerkslist"
  put "/users/:id" => "users#update"
  get "sales" => "menus#sales", as: :report
  post "datewise_search" => "menus#datewise_search"
  post "datewise_search_orders" => "orders#datewise_search"
  get "invoice" => "orders#invoice"
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  has_one_attached :image
  validates :name, presence: true
  validates :category, presence: true
  validates :price, presence: true

  def self.sort_items
    all.order(:name)
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def index
    render "index"
  end

  def create
    new_menu_item = MenuItem.new(menu_item_params)
    if new_menu_item.save
      redirect_to menu_items_path
    else
      flash[:error] = new_menu_item.errors.full_messages.join(" , ")
      redirect_to menu_items_path
    end
  end

  def update
    price = params[:price]
    id = params[:id]
    menu_item = MenuItem.find(id)
    menu_item.price = price
    menu_item.save!
    redirect_to menu_items_path
  end

  def destroy
    id = params[:id]
    menu_item = MenuItem.find(id)
    menu_item.destroy
    redirect_to menu_items_path
  end

  private def menu_item_params
    params.permit(:name, :price, :description, :category, :image)
  end
end

app/views/menu_items/_Menu-Items-List.html.erb
 <section style="padding-top: 9.77vh">
    <% menu_items.each do |menu_item| %>
        <div class="menuitems-container">

            <p class="menu-item-name"><%= menu_item.name %></p>
            <p class="menu-item-amount"><%= menu_item.price %></p>

            <div class="dropdown">
                <button class="dropbtn">
                    <i id="edittext" class="fas fa-pencil-alt fa-2x" aria-hidden = "true"></i>
                </button>
                <div class="dropdown-content">
                    <%= form_with(url: "/menu_items/#{menu_item.id}", method: "put", class: "change-price") do %>
                        <%= text_field_tag("price", nil, class: "edit-price", placeholder: "increase amount?") %>
                        <%= submit_tag("change", class: "edit-price-button") %>
                    <% end %>
                </div>
            </div>

            <%= form_with(url: "/menu_items/#{menu_item.id}", method: "delete") do %>
                <button style="background-color:Transparent;border:none" type = submit>
                    <i  id="menuitem-delete" class="fas fa-trash" aria-hidden = "true" ></i>
                </button>
            <% end %>

        </div>
    <% end %>
</section>

app/views/menu_items/index.html.erb
<section id="sideMenu">
    <div class="toggle-btn" onclick="toggleSidebar()">
        <span></span>
        <span></span>
    </div>
    <nav id="dashboard-menu">
        <a id="items" href="/menus">
            <i class="fas fa-home" aria-hidden = "true"></i>
        MENU</a>
        <a id="items" href="/active-menu">
            <i class="fab fa-meetup" aria-hidden = "true"></i>
        ACTIVE-MENU</a>
        <a id="items" href="#" class="active-dashboard">
            <i class="fas fa-utensils" aria-hidden = "true"></i>
        MENU_ITEMS</a>
        <a id="items" href="/orders">
            <i class="fas fa-history" aria-hidden = "true"></i>
        ORDERS</a>
        <a id="items" href="/users-list">
            <i class="fas fa-users" aria-hidden = "true"></i>
        USERS</a>
        <a id="items" href="/clerks-list">
            <i class="fas fa-address-card" aria-hidden = "true"></i>
        CLERKS</a>
        <a id="items" href="/sales">
            <i class="fas fa-rupee-sign" aria-hidden = "true"></i>
        SALES</a>
            <a id="items" href="/cdash">
            <i class="fas fa-cookie-bite" aria-hidden = "true"></i>
        OFFLINE ORDER</a>
    </nav>
</section>

<header class="navigationbar">
    <diV class="dashboard-text">DASHBOARD</div>
        <div class="logo">
        <img class="navbar-brand" src="<%= asset_path('logo.png') %>" />
    </div>
    <p class="restaurantname">CHEFOODU</p>
        <a
            href="#"
            class="nav-link dropdown-toggle"
            id="logout"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
            >
            <i id="loggedin-icon" class="fas fa-user-circle fa-3x" aria-hidden = "true"></i>
            </a>
            <div
            class="dropdown-menu dropdown-menu-right"
            aria-labelledby="logout"
            >
            <p class="logout-link"><%= link_to "Sign-out", destroy_session_path, method: "delete" %></p>
            </div>
</header>

<section class="New-Menu-Item">
    <%= form_with(url: "/menu_items", method: "POST", class: "Add-Menu-item") do |f| %>

        <%= f.text_field("name", class: "Menu-item-Name", placeholder: "Bored Of Existing Menus Items?") %>
        <%= f.number_field("price", class: "Menu-item-price", placeholder: "A Bit More Cheaper") %>
        <%= f.text_field("description", class: "Menu-item-description", placeholder: "Anything Special About The Food Item?") %>
        <%= f.text_field("category", class: "Menu-item-category", placeholder: "Category?") %>
        <div class= "Menu-item-image">
            <p class="image-text">IMAGE</p>
            <%= f.file_field :image %>
        </div>
        <%= f.submit("Add", class: "Addmenu-item-Button") %>

    <% end %>
</section>

<section>
    <%= render partial: "Menu-Items-List", locals: { menu_items: MenuItem.all } %>
</section>

<script>
    function toggleSidebar(){
    document.getElementById("sideMenu").classList.toggle('active');
    }
</script>